### ISSUE TITLE
NCCL 2.8.4 for CUDA 11.2

### ISSUE THREAD

**Issue by lemairecarl** [ComputeCanada/easybuild-easyconfigs#41]
I was trying to build TensorFlow with CUDA 11.2 and NCCL 2.8.4. While that [NCCL version does support that CUDA version](https://docs.nvidia.com/deeplearning/nccl/release-notes/rel_2-8-4.html#rel_2-8-4), our current NCCL 2.8.4 module does not accept to be loaded with CUDA 11.2.

Not sure what is the fix. Does it suffice to copy that file and change that line:
https://github.com/ComputeCanada/easybuild-easyconfigs/blob/cef57c7a1f415913011a338de8084e77312a4fb5/easybuild/easyconfigs/n/NCCL/NCCL-2.8.4-CUDAcore-11.1.1.eb#L10

Also, I'm wondering why this line contains `cuda11.2`... Shouldn't it be `cuda11.1` ?
https://github.com/ComputeCanada/easybuild-easyconfigs/blob/cef57c7a1f415913011a338de8084e77312a4fb5/easybuild/easyconfigs/n/NCCL/NCCL-2.8.4-CUDAcore-11.1.1.eb#L15

Thanks

**Comment by lemairecarl** [comment]
Paging @ccoulombe since you are the author of that eb file

**Comment by ccoulombe** [comment]
Why opening an issue? I can build a newer version if needed.
The cuda11.2 is compatible with cuda 11.1 per the release notes.

**Comment by ccoulombe** [comment]
I'll close this since we are already discussing this on Slack.
